pipeline {
    agent any 
    stages{
        stage('BUILD') {
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD stage"
                    exit 1
                '''
            }
        }

        stage('TEST') {
            steps{
                sh '''
                    sleep 6
                    echo "This is a TEST stage"
                '''
            }
        }

        stage('DEPLOY') {
            steps{
                sh '''
                    sleep 5
                    echo "This is a DEPLOY stage"
                    exit 0
                '''
            }
        }
    }
}

